AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'

Documentation:
  Enabled: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true
  # When true, forces the alignment of `=` in assignments on consecutive lines.
  ForceEqualSignAlignment: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  # When `true`, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

### Metrics

# Line count of things
Metrics/ClassLength:
  Max: 2000
  Enabled: false
Metrics/ModuleLength:
  Max: 1000
  Enabled: false
Metrics/MethodLength:
  Max: 100
  Enabled: false
Metrics/BlockLength:
  Max: 100
  Enabled: false
Metrics/BlockNesting:
  Max: 7
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Enabled: false

Naming/PredicateName:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/HandleExceptions:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 53
Metrics/ParameterLists:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 58

Security/Eval:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/EmptyElse:
  Enabled: true
Style/EmptyLiteral:
  Enabled: true
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: true
Style/WordArray:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals
Style/NegatedIf:
  Enabled: false
Style/SafeNavigation:
  Description: 'Use safe navigation (&.) instead of checking if an object exists before calling the method.'
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false

Style/CommentedKeyword:
  Description: 'Do not place comments on the same line as certain keywords.'
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  Enabled: false
