require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/schema.rb'

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/ExtraSpacing:
  # When true, allows most uses of extra spacing if the intent is to align
  # things with the previous or next line, not counting empty lines or comment
  # lines.
  AllowForAlignment: true
  # When true, forces the alignment of `=` in assignments on consecutive lines.
  ForceEqualSignAlignment: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  # When `true`, allows most uses of extra spacing if the intent is to align
  # with an operator on the previous or next line, not counting empty lines
  # or comment lines.
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

### Metrics

# Line count of things
Metrics/ClassLength:
  Max: 2000
  Enabled: false
Metrics/LineLength:
  Max: 120
  Enabled: false
Metrics/ModuleLength:
  Max: 1000
  Enabled: false
Metrics/MethodLength:
  Max: 100
  Enabled: false
Metrics/BlockLength:
  Max: 100
  Enabled: false
Metrics/BlockNesting:
  Max: 7
Metrics/AbcSize:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/EmptyEnsure:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/SuppressedException:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 53
Metrics/ParameterLists:
  Max: 9
Metrics/PerceivedComplexity:
  Max: 58

Security/Eval:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - spec/factories/**/*.rb

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: true
Style/EmptyLiteral:
  Enabled: true
Style/EmptyCaseCondition:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: true
Style/WordArray:
  Enabled: false
Style/AndOr:
  EnforcedStyle: conditionals

Style/SafeNavigation:
  Description: 'Use safe navigation (&.) instead of checking if an object exists before calling the method.'
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/CommentedKeyword:
  Description: 'Do not place comments on the same line as certain keywords.'
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# A specialized exception class will take one or more arguments and construct the message from it.
# So both variants make sense.
Style/RaiseArgs:
  Enabled: false

# Fail is an alias of raise. Avoid aliases, it's more cognitive load for no gain.
# The argument that fail should be used to abort the program is wrong too,
# there's Kernel#abort for that.
Style/SignalException:
  EnforcedStyle: only_raise

Rails/Date:
  EnforcedStyle: flexible

Rails/TimeZone:
  EnforcedStyle: flexible

# new rules added from upgrading version. we need to evaluate before turning them on
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: false
Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: false
Gemspec/RequireMFA: # new in 1.23
  Enabled: false
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: false
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: false
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: false
Lint/AmbiguousAssignment: # new in 1.7
  Enabled: false
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: false
Lint/AmbiguousRange: # new in 1.19
  Enabled: false
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: false
Lint/DeprecatedConstants: # new in 1.8
  Enabled: false
Lint/DuplicateBranch: # new in 1.3
  Enabled: false
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: false
Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: false
Lint/EmptyBlock: # new in 1.1
  Enabled: false
Lint/EmptyClass: # new in 1.3
  Enabled: false
Lint/EmptyInPattern: # new in 1.16
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: false
Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: false
Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: false
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: false
Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: false
Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: false
Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: false
Lint/RefinementImportMethods: # new in 1.27
  Enabled: false
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: false
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: false
Lint/SymbolConversion: # new in 1.9
  Enabled: false
Lint/ToEnumArguments: # new in 1.1
  Enabled: false
Lint/TripleQuotes: # new in 1.9
  Enabled: false
Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: false
Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: false
Lint/UselessRescue: # new in 1.43
  Enabled: false
Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: false
Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: false
Naming/BlockForwarding: # new in 1.24
  Enabled: false
Security/CompoundHash: # new in 1.28
  Enabled: false
Security/IoMethods: # new in 1.22
  Enabled: false
Style/ArgumentsForwarding: # new in 1.1
  Enabled: false
Style/ArrayIntersect: # new in 1.40
  Enabled: false
Style/CollectionCompact: # new in 1.2
  Enabled: false
Style/ComparableClamp: # new in 1.44
  Enabled: false
Style/ConcatArrayLiterals: # new in 1.41
  Enabled: false
Style/DataInheritance: # new in 1.49
  Enabled: false
Style/DirEmpty: # new in 1.48
  Enabled: false
Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: false
Style/EmptyHeredoc: # new in 1.32
  Enabled: false
Style/EndlessMethod: # new in 1.8
  Enabled: false
Style/EnvHome: # new in 1.29
  Enabled: false
Style/ExactRegexpMatch: # new in 1.51
  Enabled: false
Style/FetchEnvVar: # new in 1.28
  Enabled: false
Style/FileEmpty: # new in 1.48
  Enabled: false
Style/FileRead: # new in 1.24
  Enabled: false
Style/FileWrite: # new in 1.24
  Enabled: false
Style/HashConversion: # new in 1.10
  Enabled: false
Style/HashExcept: # new in 1.7
  Enabled: false
Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: false
Style/InPatternThen: # new in 1.16
  Enabled: false
Style/MagicCommentFormat: # new in 1.35
  Enabled: false
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: false
Style/MapToHash: # new in 1.24
  Enabled: false
Style/MapToSet: # new in 1.42
  Enabled: false
Style/MinMaxComparison: # new in 1.42
  Enabled: false
Style/MultilineInPatternThen: # new in 1.16
  Enabled: false
Style/NegatedIfElseCondition: # new in 1.2
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: false
Style/NilLambda: # new in 1.3
  Enabled: false
Style/NumberedParameters: # new in 1.22
  Enabled: false
Style/NumberedParametersLimit: # new in 1.22
  Enabled: false
Style/ObjectThen: # new in 1.28
  Enabled: false
Style/OpenStructUse: # new in 1.23
  Enabled: false
Style/OperatorMethodCall: # new in 1.37
  Enabled: false
Style/QuotedSymbols: # new in 1.16
  Enabled: false
Style/RedundantArgument: # new in 1.4
  Enabled: false
Style/RedundantConstantBase: # new in 1.40
  Enabled: false
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: false
Style/RedundantEach: # new in 1.38
  Enabled: false
Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: false
Style/RedundantInitialize: # new in 1.27
  Enabled: false
Style/RedundantLineContinuation: # new in 1.49
  Enabled: false
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: false
Style/RedundantStringEscape: # new in 1.37
  Enabled: false
Style/SelectByRegexp: # new in 1.22
  Enabled: false
Style/StringChars: # new in 1.12
  Enabled: false
Style/SwapValues: # new in 1.1
  Enabled: false
Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: false
Rails/ActionControllerTestCase: # new in 2.14
  Enabled: false
Rails/ActionOrder: # new in 2.17
  Enabled: false
Rails/ActiveRecordCallbacksOrder: # new in 2.7
  Enabled: false
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: false
Rails/AddColumnIndex: # new in 2.11
  Enabled: false
Rails/AfterCommitOverride: # new in 2.8
  Enabled: false
Rails/AttributeDefaultBlockValue: # new in 2.9
  Enabled: false
Rails/CompactBlank: # new in 2.13
  Enabled: false
Rails/DeprecatedActiveModelErrorsMethods: # new in 2.14
  Enabled: false
Rails/DotSeparatedKeys: # new in 2.15
  Enabled: false
Rails/DuplicateAssociation: # new in 2.14
  Enabled: false
Rails/DuplicateScope: # new in 2.14
  Enabled: false
Rails/DurationArithmetic: # new in 2.13
  Enabled: false
Rails/EagerEvaluationLogMessage: # new in 2.11
  Enabled: false
Rails/ExpandedDateRange: # new in 2.11
  Enabled: false
Rails/FindById: # new in 2.7
  Enabled: false
Rails/FreezeTime: # new in 2.16
  Enabled: false
Rails/I18nLazyLookup: # new in 2.14
  Enabled: false
Rails/I18nLocaleAssignment: # new in 2.11
  Enabled: false
Rails/I18nLocaleTexts: # new in 2.14
  Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: false
Rails/Inquiry: # new in 2.7
  Enabled: false
Rails/MailerName: # new in 2.7
  Enabled: false
Rails/MatchRoute: # new in 2.7
  Enabled: false
Rails/MigrationClassName: # new in 2.14
  Enabled: false
Rails/NegateInclude: # new in 2.7
  Enabled: false
Rails/Pluck: # new in 2.7
  Enabled: false
Rails/PluckInWhere: # new in 2.7
  Enabled: false
Rails/RedundantPresenceValidationOnBelongsTo: # new in 2.13
  Enabled: false
Rails/RedundantTravelBack: # new in 2.12
  Enabled: false
Rails/RenderInline: # new in 2.7
  Enabled: false
Rails/RenderPlainText: # new in 2.7
  Enabled: false
Rails/ResponseParsedBody: # new in 2.18
  Enabled: false
Rails/RootJoinChain: # new in 2.13
  Enabled: false
Rails/RootPathnameMethods: # new in 2.16
  Enabled: false
Rails/RootPublicPath: # new in 2.15
  Enabled: false
Rails/ShortI18n: # new in 2.7
  Enabled: false
Rails/SquishedSQLHeredocs: # new in 2.8
  Enabled: false
Rails/StripHeredoc: # new in 2.15
  Enabled: false
Rails/ThreeStateBooleanColumn: # new in 2.19
  Enabled: false
Rails/TimeZoneAssignment: # new in 2.10
  Enabled: false
Rails/ToFormattedS: # new in 2.15
  Enabled: false
Rails/ToSWithArgument: # new in 2.16
  Enabled: false
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: false
Rails/TransactionExitStatement: # new in 2.14
  Enabled: false
Rails/UnusedIgnoredColumns: # new in 2.11
  Enabled: false
Rails/WhereEquals: # new in 2.9
  Enabled: false
Rails/WhereExists: # new in 2.7
  Enabled: false
Rails/WhereMissing: # new in 2.16
  Enabled: false
Rails/WhereNot: # new in 2.8
  Enabled: false
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: false
