coffeescript:
  enabled: false
  config_file: coffeescript/coffeelint.json

credo:
  enabled: true
  config_file: elixir/.credo.exs

eslint:
  enabled: true
  config_file: javascript/.eslintrc.json

flake8:
  enabled: true
  config_file: python/.flake8

ruby:
  enabled: true
  config_file: ruby/.rubocop.yml

scss:
  enabled: true
  config_file: sass/.scss-lint.yml
