coffeescript:
  enabled: false
  config_file: coffeescript/coffeelint.json

eslint:
  enabled: true
  config_file: javascript/.eslintrc.json

ruby:
  enabled: true
  config_file: ruby/.rubocop.yml

scss:
  enabled: true
  config_file: sass/.scss-lint.yml
