coffeescript:
  enabled: false
  config_file: coffeescript/coffeelint.json

credo:
  enabled: true
  config_file: elixir/.credo.exs

eslint:
  enabled: false

flake8:
  enabled: true
  config_file: python/.flake8
  
javascript:
  enabled: false

ruby:
  enabled: true
  config_file: ruby/.rubocop.yml

rubocop:
  enabled: true
  version: 1.22.1
  config_file: ruby/.rubocop.yml

scss:
  enabled: true
  config_file: sass/.scss-lint.yml
